name: Musepose_train_midup_3x_loaded
description: This is yanghaotian project
workspace: yanghaotian
project: yanghaotian
resources:
  resource_pool: A10040G_NVLINK_device
  slots_per_trial: 1    
  max_slots: 2
bind_mounts:
  - host_path: /home/fds-admin/determinedai_files
    container_path: /home/fds-admin/determinedai_files
  - host_path: /home/fds-admin/user_files
    container_path: /home/fds-admin/user_files
environment:
  force_pull_image: true
  image: 100.74.185.9:80/yanghaotian/train_pose:251229
  registry_auth:
    username: yanghaotian
    password: Fds00000000
searcher:
  name: single
  metric: accuracy
entrypoint: >
  pip install protobuf==3.20.3; cd /home/fds-admin/user_files/yanghaotian/yanghaotian/test/Musepose_copy1; python train_stage_1_multiGPU_comp_loaded.py;

# /opt/conda/envs/DiffGui/bin/python scripts/sample.py --outdir ./outputs --config ./configs/sample/sample.yml --device cuda:0

