pretrained_base_model_path: './pretrained_weights/sd-image-variations-diffusers'
pretrained_vae_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/image_encoder'



# denoising_unet_path: "./pretrained_weights/MusePose/denoising_unet.pth"
# reference_unet_path: "./pretrained_weights/MusePose/reference_unet.pth"
# pose_guider_path: "./pretrained_weights/MusePose/pose_guider.pth"
# motion_module_path: "./pretrained_weights/MusePose/motion_module.pth"

denoising_unet_path: /home/yanghaotian/server_data/yanghaotian/test/MusePose/exp_output/stage_1/denoising_unet-130200.pth
reference_unet_path: /home/yanghaotian/server_data/yanghaotian/test/MusePose/exp_output/stage_1/reference_unet-130200.pth
pose_guider_path: /home/yanghaotian/server_data/yanghaotian/test/MusePose/exp_output/stage_1/pose_guider-130200.pth
motion_module_path: "/home/yanghaotian/server_data/yanghaotian/test/MusePose/exp_output/stage_2/motion_module-2517.pth"



inference_config: "./configs/inference_v2.yaml"
weight_dtype: 'fp16'



test_cases:
  "./assets/images/ref.png":
    - "./assets/poses/align/img_ref_video_00015.mp4"
